### ISSUE TITLE
!skip should always create a plain NSView

### ISSUE THREAD

**Issue by hbons** [netonjm/FigmaSharp#218]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/103326/81730764-4e691d80-948e-11ea-8082-558b581b052e.png">

Now it's looking at the object type. Ignore object type and create the NSView with the name and dimensions (those last 2 work fine).

**Comment by netonjm** [comment]
Here the problem is not the expected. By default in our service process we skip views starting with "!" if I remember correctly, but in this case because you are adding a name, this is basically generating the corresponding code, and in this case all the Rectangles are rendered by a NSImageView because historical reasons, but now this needs to be changed to render as NSView
