### ISSUE TITLE
Investigate how to handle templated lists

### ISSUE THREAD

**Issue by Therzok** [netonjm/FigmaSharp#53]
Currently, some figma designs have hard coded list items.

What is the process to `template-ize` the list so it doesn't render the content, but allows for MVVM/MVC integration?

**Comment by hbons** [comment]
Yea we should invent some logic for this.

My initial idea was too treat Figma components as classes. So components (that are not macOS components) will generate a class with all the layout properties. All instances of it will be ignored. Usually this is detectable because they're many instances in the same group.

**Comment by netonjm** [comment]
If I understand correctly the issue that's already handled by using custom code converters. But it's true this completely changes how is this implemented from a Extension context. I'm working in a prototype for 0.1 or 0.2 milestone.

**Comment by hbons** [comment]
@Therzok  let me know what you think about the ideas in #109. it should cover these cases.

**Comment by Therzok** [comment]
Yeah, #109 should handle this.

**Comment by netonjm** [comment]
#109 is basically inheritance from layers, but nothing related to MVVM, which in code generation will need in the target project include a reference of a Figma library with some abstraction to handle this
